import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ChakraProviderWrapper from './chakra-provider';
import ClientProviderRedux from './reduxProvider/reduxProvider'

/**
 * O Next 14 ou versão recente nao aceitou o Provider do Redux diretamente envolvendo
 * outros Provider, há um conflito de ambiente de Server e Client do Next, o Redux precisa
 * ser rodado dentro do ambiente Client e esse componente Layout apenas no Server
 * Para combater esse erro eu criei um provider externo que roda do lado do cliente
 * e apenas chamo ele aqui quando já rodou do lado do cliente e assim consigo rodar ambos
 * sem erros.
 */

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProviderWrapper>
          <ClientProviderRedux>
            {children}
          </ClientProviderRedux>
        </ChakraProviderWrapper>
      </body>
    </html>
  );
}
